# Generated by Django 5.0.2 on 2024-02-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall_of_america', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0, help_text='Enter a discount in percents (%)'),
        ),
    ]
